# Generated by Django 5.1.2 on 2024-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year_of_manufacture', models.IntegerField()),
                ('vehicle_class_type', models.CharField(choices=[('SUV', 'SUV'), ('limousine', 'Limousine'), ('sedan', 'Sedan'), ('sports car', 'Sports Car'), ('luxury bus', 'Luxury Bus')], max_length=20)),
                ('number_plate', models.CharField(max_length=15, unique=True)),
                ('colour', models.CharField(max_length=50)),
                ('inspection_certificate', models.FileField(upload_to='inspection_certificates/')),
                ('vehicle_image', models.ImageField(upload_to='vehicle_images/')),
                ('owner_first_name', models.CharField(max_length=50)),
                ('owner_last_name', models.CharField(max_length=50)),
                ('owner_phone_number', models.CharField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
                ('privately_owned', models.BooleanField(default=True)),
                ('vehicle_insurance', models.FileField(upload_to='vehicle_insurances/')),
                ('insurance_policy_number', models.CharField(max_length=50)),
                ('insurance_provider', models.CharField(max_length=100)),
                ('insurance_expiry_date', models.DateField()),
                ('specifications', models.TextField(blank=True, null=True)),
                ('additional_amenities', models.TextField(blank=True, null=True)),
                ('seating_capacity', models.IntegerField()),
                ('accessibility_features', models.TextField(blank=True, null=True)),
                ('fuel_type', models.CharField(max_length=20)),
                ('engine_capacity', models.FloatField()),
                ('event_suitability', models.CharField(max_length=100)),
                ('chauffeur_or_driver_available', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('in service', 'In Service')], max_length=20)),
                ('main_service', models.JSONField(default=dict)),
                ('pick_up_point', models.CharField(max_length=100)),
                ('drop_off_point', models.CharField(max_length=100)),
                ('booking_history', models.JSONField(default=list)),
                ('pricing', models.JSONField(default=dict)),
                ('deposit_required', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(max_length=100)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('reported_incidents', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('gps_tracking_status', models.BooleanField(default=True)),
                ('security_features', models.TextField(blank=True, null=True)),
                ('admin_authorization_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Approval'), ('denied', 'Denied')], max_length=20)),
                ('admin_permission_for_chauffeurs', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
