# Generated by Django 5.1.2 on 2024-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('chauffeur_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('residence', models.CharField(max_length=100)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_residency', models.CharField(max_length=100)),
                ('drivers_license_number', models.CharField(max_length=50)),
                ('drivers_license_expiry_date', models.DateField()),
                ('drivers_license', models.FileField(upload_to='drivers_licenses/')),
                ('psv_license_number', models.CharField(max_length=50)),
                ('psv_license', models.FileField(upload_to='psv_licenses/')),
                ('years_of_experience_certificate', models.FileField(upload_to='experience_certificates/')),
                ('defensive_driving_certificate', models.FileField(upload_to='defensive_driving_certificates/')),
                ('police_clearance_certificate', models.FileField(upload_to='clearance_certificates/')),
                ('national_id_number', models.CharField(max_length=50)),
                ('national_id', models.FileField(upload_to='national_ids/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('chauffeur_rating', models.FloatField(default=0)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('customer_reviews', models.TextField(blank=True, null=True)),
                ('reported_incidents', models.TextField(blank=True, null=True)),
                ('account_creation_date', models.DateField(auto_now_add=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=10)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('availability', models.JSONField(default=dict)),
                ('operating_area_preference', models.JSONField(default=list)),
                ('languages_spoken', models.JSONField(default=list)),
                ('gps_tracking_enabled', models.BooleanField(default=True)),
                ('confidentiality_permission', models.BooleanField(default=True)),
            ],
        ),
    ]
