# Generated by Django 5.1.2 on 2024-10-29 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=50)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.FloatField()),
                ('payment_status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_information', models.CharField(max_length=100)),
                ('billing_address', models.CharField(max_length=100)),
                ('payment_method', models.CharField(choices=[('mobile money', 'Mobile Money'), ('cash', 'Cash')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('date_of_invoice', models.DateField()),
                ('charges_list', models.JSONField(default=dict)),
                ('total_amount_due', models.FloatField()),
                ('total_amount_paid', models.FloatField()),
                ('linked_driver_or_chauffeur_id', models.CharField(max_length=50)),
                ('amount_earned', models.FloatField()),
                ('commission_rate_deducted', models.FloatField()),
                ('transaction_logs', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('dispute_status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('declined', 'Declined')], max_length=20)),
                ('dispute_details', models.TextField(blank=True, null=True)),
                ('usage_insights', models.JSONField(default=dict)),
                ('refund_status', models.CharField(choices=[('processed', 'Processed'), ('pending', 'Pending'), ('declined', 'Declined')], max_length=20)),
                ('refund_amount', models.FloatField(blank=True, null=True)),
                ('refund_reason', models.TextField(blank=True, null=True)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
