CREATE TABLE Users (
    user_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    profile_picture BYTEA,
    residence_location VARCHAR(100),
    work_location VARCHAR(100),
    additional_location VARCHAR(100),
    trips_taken INT DEFAULT 0
);

CREATE TABLE Drivers (
    driver_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    current_residency VARCHAR(100),
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    drivers_license_number VARCHAR(50) UNIQUE NOT NULL,
    drivers_license_expiry DATE,
    drivers_license BYTEA,
    psv_license_number VARCHAR(50),
    psv_license BYTEA,
    national_id_number VARCHAR(50) UNIQUE,
    national_id BYTEA,
    profile_picture BYTEA,
    police_clearance_certificate BYTEA,
    police_clearance_number VARCHAR(50),
    vehicle_make VARCHAR(50),
    vehicle_model VARCHAR(50),
    vehicle_year_of_make INT,
    vehicle_registration_number VARCHAR(20),
    vehicle_colour VARCHAR(20),
    vehicle_insurance_policy_number VARCHAR(50),
    vehicle_insurance_expiry DATE,
    vehicle_insurance BYTEA,
    driver_rating FLOAT CHECK (driver_rating >= 1 AND driver_rating <= 5),
    completed_rides INT DEFAULT 0,
    customer_review TEXT,
    incident_report TEXT,
    account_status VARCHAR(20) CHECK (account_status IN ('active', 'inactive', 'suspended')),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_active_date TIMESTAMP,
    login_history JSONB,
    payment_methods VARCHAR(50),
    earning_history NUMERIC,
    app_commission NUMERIC,
    trips_made INT
);

CREATE TABLE Chauffeurs (
    chauffeur_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    residence VARCHAR(100),
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    emergency_contact_residence VARCHAR(100),
    drivers_license_number VARCHAR(50) UNIQUE NOT NULL,
    drivers_license_expiry DATE,
    drivers_license BYTEA,
    psv_license_number VARCHAR(50),
    psv_license BYTEA,
    experience_certification BYTEA,
    defensive_driving_certificate BYTEA,
    police_clearance_certificate BYTEA,
    national_id_number VARCHAR(50) UNIQUE,
    national_id BYTEA,
    profile_picture BYTEA,
    chauffeur_rating FLOAT CHECK (chauffeur_rating >= 1 AND chauffeur_rating <= 5),
    completed_jobs INT DEFAULT 0,
    customer_reviews TEXT,
    incident_report TEXT,
    account_status VARCHAR(20) CHECK (account_status IN ('active', 'inactive', 'suspended')),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_active_date TIMESTAMP,
    availability_hours INT,
    availability_days INT,
    preferred_areas JSONB,
    languages_spoken VARCHAR[],
    gps_tracking_enabled BOOLEAN DEFAULT FALSE,
    confidentiality_permission BOOLEAN
);

CREATE TABLE Vehicles (
    vehicle_id SERIAL PRIMARY KEY,
    make VARCHAR(50),
    model VARCHAR(50),
    year_of_manufacture INT,
    class_type VARCHAR(20) CHECK (class_type IN ('SUV', 'limousine', 'sedan', 'sports car', 'luxury bus')),
    number_plate VARCHAR(20) UNIQUE,
    color VARCHAR(20),
    inspection_certificate BYTEA,
    images BYTEA[],
    owner_first_name VARCHAR(50),
    owner_last_name VARCHAR(50),
    owner_phone VARCHAR(20),
    owner_email VARCHAR(100),
    ownership_type VARCHAR(20) CHECK (ownership_type IN ('private', 'leased')),
    insurance_certificate BYTEA,
    insurance_policy_number VARCHAR(50),
    insurance_provider VARCHAR(50),
    insurance_expiry DATE,
    specifications JSONB,
    amenities JSONB,
    seating_capacity INT,
    accessibility_features TEXT,
    fuel_type VARCHAR(20),
    engine_capacity VARCHAR(20),
    event_suitability VARCHAR(100),
    availability_status VARCHAR(20) CHECK (availability_status IN ('available', 'booked', 'in service')),
    event_type VARCHAR(50),
    service_type VARCHAR(50) CHECK (service_type IN ('point-to-point', 'wait-at-destination', 'round-trip')),
    pickup_point VARCHAR(100),
    dropoff_point VARCHAR(100),
    booking_history JSONB,
    pricing NUMERIC,
    deposit_required BOOLEAN DEFAULT FALSE,
    payment_terms TEXT,
    feedback TEXT,
    reported_incidents TEXT,
    rating FLOAT CHECK (rating >= 1 AND rating <= 5),
    gps_tracking_status BOOLEAN,
    security_features BOOLEAN,
    admin_authorization_status VARCHAR(20) CHECK (admin_authorization_status IN ('approved', 'pending approval', 'denied')),
    admin_permission BOOLEAN,
    admin_notes TEXT
);

CREATE TABLE Payments (
    transaction_id SERIAL PRIMARY KEY,
    booking_id INT,
    transaction_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    amount_paid NUMERIC NOT NULL,
    payment_status VARCHAR(20) CHECK (payment_status IN ('completed', 'pending', 'failed', 'refunded')),
    customer_id INT REFERENCES Users(user_id),
    customer_name VARCHAR(100),
    customer_contact VARCHAR(20),
    billing_address VARCHAR(150),
    payment_method VARCHAR(50) CHECK (payment_method IN ('mobile money', 'cash')),
    invoice_number VARCHAR(50),
    invoice_date DATE,
    charges JSONB,
    tax_fees NUMERIC,
    total_amount NUMERIC,
    driver_chauffeur_id INT,
    earnings NUMERIC,
    commission_rate NUMERIC,
    transaction_logs JSONB,
    dispute_status VARCHAR(20),
    dispute_details TEXT,
    usage_insights JSONB,
    refund_status VARCHAR(20) CHECK (refund_status IN ('processed', 'pending', 'declined')),
    refund_amount NUMERIC,
    refund_reason TEXT,
    refund_date DATE
);
