# Generated by Django 5.1.2 on 2024-10-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('residence_location', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('add_location', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_trips_taken', models.IntegerField(default=0)),
            ],
        ),
    ]
